name: 02 - Workflow Events
on: 
    push:
    pull_request:
    workflow_dispatch:
    schedule: 
        - cron: "5 4 * * *"
    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: Show the trigger
              run: echo "This event was triggered by: ${{github.event_name}}"

        